In [1]:
import pandas as pd
import numpy as np
from sklearn import svm

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel("Psycology.xls")
df.head()

,เพศ,อายุ,เคยมีแฟนมาแล้ว (คน),จำนวนครั้งที่ไปออกกำลังกายต่อสัปดาห์,ระยะเวลาการนอน,นิสิยการกินอาหาร,เคยคิดฆ่าตัวตาย,จำนวนชั่วโมงที่เข้าห้องสมุดในหนึ่งสัปดาห์,ระดับความเครียดด้านการเงิน,เคยกินยานอนหลับ,ภาวะซึมเศร้า
0,Male,28,5,3,5-6 ชั่วโมง,อาหารสุขภาพ,Yes,8,3,Yes,Yes
1,Male,23,5,2,มากกว่า 8 ชั่วโมง,อาหารทั่วไป,No,10,4,No,Yes
2,Female,23,1,3,น้อยกว่า 5 ชั่วโมง,อาหารสุขภาพ,Yes,0,3,No,No
3,Female,20,5,5,มากกว่า 8 ชั่วโมง,Junkfood,Yes,2,5,No,Yes
4,Male,29,4,3,มากกว่า 8 ชั่วโมง,Junkfood,Yes,1,3,No,Yes

In [7]:
cl = {
    'เพศ': 'Sex',
    'อายุ': 'Age',
    'เคยมีแฟนมาแล้ว  (คน)': 'GirlfriendCount',
    'จำนวนครั้งที่ไปออกกำลังกายต่อสัปดาห์': 'ExercisePerWeek',
    'ระยะเวลาการนอน': 'SleepingTime',
    'นิสิยการกินอาหาร': 'FoodEatingBehavior',
    'เคยคิดฆ่าตัวตาย': 'SuicidalThoughts',
    'จำนวนชั่วโมงที่เข้าห้องสมุดในหนึ่งสัปดาห์': 'LibraryTimePerWeek',
    'ระดับความเครียดด้านการเงิน': 'MoneyStress',
    'เคยกินยานอนหลับ': 'SleepingPills',
    'ภาวะซึมเศร้า': 'Sadness'
}

df.rename(columns=cl, inplace=True)
df.head()

,Sex,Age,GirlfriendCount,ExercisePerWeek,SleepingTime,FoodEatingBehavior,SuicidalThoughts,LibraryTimePerWeek,MoneyStress,SleepingPills,Sadness
0,Male,28,5,3,5-6 ชั่วโมง,อาหารสุขภาพ,Yes,8,3,Yes,Yes
1,Male,23,5,2,มากกว่า 8 ชั่วโมง,อาหารทั่วไป,No,10,4,No,Yes
2,Female,23,1,3,น้อยกว่า 5 ชั่วโมง,อาหารสุขภาพ,Yes,0,3,No,No
3,Female,20,5,5,มากกว่า 8 ชั่วโมง,Junkfood,Yes,2,5,No,Yes
4,Male,29,4,3,มากกว่า 8 ชั่วโมง,Junkfood,Yes,1,3,No,Yes